### ISSUE TITLE
As a user, I want to be able to create Todo items

### ISSUE THREAD

**Issue by zacherygentry** [zacherygentry/CSE-4322-Project-3#10]
In the views folder, create a file called CreateTodoView.dart
- This will be a stateful widget that allows for user input to create a todo item
- To navigate here, the user should press a [FloatingActionButton](https://api.flutter.dev/flutter/material/FloatingActionButton-class.html).
  - Add this FloatingActionButton to the homescreen of the app, and use Navigator.push to get to the new view.
    - Follow [this](https://flutter.dev/docs/cookbook/navigation/navigation-basics) for how to setup basic navigation

**Comment by ij2872** [comment]
**1 Hour**
Completed! shared_prefrence is up next. showModalBottomSheet() was used instead of making a new view 🤦‍♂
