### ISSUE TITLE
As a user, I want to be able to mark todo items as completed

### ISSUE THREAD

**Issue by zacherygentry** [zacherygentry/CSE-4322-Project-3#13]
From the home screen, users should be able to swipe right to mark their todo as completed.
Completing a todo item will mark through the todo's text, and move the item to the bottom of the todo list, signifying it has been completed.
- Check out the [Dismissible ](https://api.flutter.dev/flutter/widgets/Dismissible-class.html) class on how to implement functionality like this

**Comment by ij2872** [comment]
**30 mins**
