### ISSUE TITLE
Todo items should be stored between sessions

### ISSUE THREAD

**Issue by zacherygentry** [zacherygentry/CSE-4322-Project-3#15]
After adding, editing or removing a todo item, it should be stored to the phone.
Let's use the [Shared Preferences](https://pub.dev/packages/shared_preferences) package to handle this.

- Update the TodoItem data model by adding toJson() and fromJson() methods to it.
- Following [this](https://medium.com/better-programming/flutter-how-to-save-objects-in-sharedpreferences-b7880d0ee2e4) should get you there.
- Let Zach know if you're having issues getting it implemented.

**Comment by ij2872** [comment]
**1 Hour**
