### ISSUE TITLE
As a user, I want to see my To-Do list items on the home screen of the app.

### ISSUE THREAD

**Issue by zacherygentry** [zacherygentry/CSE-4322-Project-3#5]
- In the widgets folder, create a file called TodoListWidget.
  - This widget should take in a List of TodoWidget)
- Create a [ListView](https://api.flutter.dev/flutter/widgets/ListView-class.html) on this new widget and design a nice looking view where each Todo is presented to the user

**Comment by ij2872** [comment]
1 Hour
