### ISSUE TITLE
Create ToDoWidget

### ISSUE THREAD

**Issue by zacherygentry** [zacherygentry/CSE-4322-Project-3#6]
- In the widgets folder, create a file called ToDoWidget.dart
- This should be a StatelessWidget that takes in a ToDoItem
  - It should represent the ToDo item in a nice, presentable way
  - Probably want to use a [Row](https://api.flutter.dev/flutter/widgets/Row-class.html) with [Text](https://flutter.dev/docs/development/ui/widgets/text) components as children

**Comment by ij2872** [comment]
Completed!

**Comment by ij2872** [comment]
Also time spent ~2 hours.
